import BigNumber from "bignumber.js";
export declare const PERCENTAGE_FACTOR: string;
export declare const HALF_PERCENTAGE: string;
export declare const WAD: string;
export declare const HALF_WAD: string;
export declare const RAY: string;
export declare const HALF_RAY: string;
export declare const WAD_RAY_RATIO: string;
export declare const oneEther: BigNumber;
export declare const oneUsd: BigNumber;
export declare const oneRay: BigNumber;
export declare const MAX_UINT_AMOUNT = "115792089237316195423570985008687907853269984665640564039457584007913129639935";
export declare const ONE_YEAR = "31536000";
export declare const ZERO_ADDRESS = "0x0000000000000000000000000000000000000000";
export declare const ONE_ADDRESS = "0x0000000000000000000000000000000000000001";
export declare const OPTIMAL_UTILIZATION_RATE: BigNumber;
export declare const EXCESS_UTILIZATION_RATE: BigNumber;
export declare const APPROVAL_AMOUNT_LENDING_POOL = "1000000000000000000000000000";
export declare const TOKEN_DISTRIBUTOR_PERCENTAGE_BASE = "10000";
export declare const MOCK_USD_PRICE_IN_WEI = "5848466240000000";
export declare const USD_ADDRESS = "0x10F7Fc1F91Ba351f9C629c5947AD69bD03C05b96";
export declare const AAVE_REFERRAL = "0";
export declare const MOCK_CHAINLINK_AGGREGATORS_PRICES: {
    AAVE: string;
    BAT: string;
    BUSD: string;
    DAI: string;
    ENJ: string;
    KNC: string;
    LINK: string;
    MANA: string;
    MKR: string;
    REN: string;
    SNX: string;
    SUSD: string;
    TUSD: string;
    UNI: string;
    USDC: string;
    USDT: string;
    WETH: string;
    WBTC: string;
    YFI: string;
    ZRX: string;
    OP: string;
    ThreeCRV: string;
    sUSD3CRV: string;
    wstETHCRV: string;
    UniDAIWETH: string;
    UniWBTCWETH: string;
    UniAAVEWETH: string;
    UniBATWETH: string;
    UniDAIUSDC: string;
    UniCRVWETH: string;
    UniLINKWETH: string;
    UniMKRWETH: string;
    UniRENWETH: string;
    UniSNXWETH: string;
    UniUNIWETH: string;
    UniUSDCWETH: string;
    UniWBTCUSDC: string;
    UniYFIWETH: string;
    BptWBTCWETH: string;
    BptBALWETH: string;
    WMATIC: string;
    STAKE: string;
    WAVAX: string;
    USD: string;
    Tricrypto2: string;
    ThreePool: string;
    StethEth: string;
    Steth: string;
    wstETH: string;
    FraxUSDC: string;
    Frax3Crv: string;
    FRAX: string;
    BAL: string;
    CRV: string;
    CVX: string;
    BADGER: string;
    LDO: string;
    ALCX: string;
    Oneinch: string;
    yvTricrypto2: string;
    yvThreePool: string;
    yvStethEth: string;
    yvFraxUSDC: string;
    yvFrax3Crv: string;
    mooCurveFsUSD: string;
    mooCurveWSTETH: string;
    velo_rETHWETH: string;
    velo_wstETHWETH: string;
    moo_velo_wstETHWETH: string;
    velo_USDCsUSD: string;
    moo_velo_USDCsUSD: string;
    velo_ETHUSDC: string;
    moo_velo_ETHUSDC: string;
    velo_OPETH: string;
    moo_velo_OPETH: string;
    velo_ETHSNX: string;
    moo_velo_ETHSNX: string;
    velo_OPUSDC: string;
    moo_velo_OPUSDC: string;
    velo_DAIUSDC: string;
    moo_velo_DAIUSDC: string;
    velo_FRAXUSDC: string;
    moo_velo_FRAXUSDC: string;
    velo_USDTUSDC: string;
    moo_velo_USDTUSDC: string;
    beethoven_USDCDAI: string;
    beethoven_wstETHETH: string;
    beethoven_WETHOPUSDC: string;
    rETH: string;
    beethoven_rETHETH: string;
    yvUSDC: string;
    yvDAI: string;
    yvUSDT: string;
    yvWETH: string;
    LUSD: string;
    velo_LUSDWETH: string;
    velo_LUSDUSDC: string;
};
export declare const chainlinkAggregatorProxy: {
    main: string;
    hardhat: string;
    localhost: string;
    kovan: string;
    matic: string;
    mumbai: string;
    avalanche: string;
    fuji: string;
    tenderly: string;
    "arbitrum-rinkeby": string;
    arbitrum: string;
    rinkeby: string;
};
export declare const chainlinkEthUsdAggregatorProxy: {
    main: string;
    hardhat: string;
    localhost: string;
    kovan: string;
    matic: string;
    mumbai: string;
    avalanche: string;
    fuji: string;
    tenderly: string;
    "arbitrum-rinkeby": string;
    arbitrum: string;
    rinkeby: string;
};
export declare const reserveAssets: Map<string, string>;
export declare const RANDOM_ADDRESSES: string[];
