/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer } from "ethers";
import { Provider } from "@ethersproject/providers";

import type { ICurvePool } from "./ICurvePool";

export class ICurvePoolFactory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ICurvePool {
    return new Contract(address, _abi, signerOrProvider) as ICurvePool;
  }
}

const _abi = [
  {
    inputs: [],
    name: "get_virtual_price",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];
