/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface TokenReserveDataInterface extends ethers.utils.Interface {
  functions: {
    "getType()": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "getType", values?: undefined): string;

  decodeFunctionResult(functionFragment: "getType", data: BytesLike): Result;

  events: {};
}

export class TokenReserveData extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: TokenReserveDataInterface;

  functions: {
    getType(overrides?: CallOverrides): Promise<{
      0: [
        {
          configuration: { data: BigNumber; 0: BigNumber };
          liquidityIndex: BigNumber;
          variableBorrowIndex: BigNumber;
          currentLiquidityRate: BigNumber;
          currentVariableBorrowRate: BigNumber;
          currentStableBorrowRate: BigNumber;
          lastUpdateTimestamp: number;
          aTokenAddress: string;
          stableDebtTokenAddress: string;
          variableDebtTokenAddress: string;
          interestRateStrategyAddress: string;
          id: number;
          tranche: number;
          0: { data: BigNumber; 0: BigNumber };
          1: BigNumber;
          2: BigNumber;
          3: BigNumber;
          4: BigNumber;
          5: BigNumber;
          6: number;
          7: string;
          8: string;
          9: string;
          10: string;
          11: number;
          12: number;
        },
        {
          configuration: { data: BigNumber; 0: BigNumber };
          liquidityIndex: BigNumber;
          variableBorrowIndex: BigNumber;
          currentLiquidityRate: BigNumber;
          currentVariableBorrowRate: BigNumber;
          currentStableBorrowRate: BigNumber;
          lastUpdateTimestamp: number;
          aTokenAddress: string;
          stableDebtTokenAddress: string;
          variableDebtTokenAddress: string;
          interestRateStrategyAddress: string;
          id: number;
          tranche: number;
          0: { data: BigNumber; 0: BigNumber };
          1: BigNumber;
          2: BigNumber;
          3: BigNumber;
          4: BigNumber;
          5: BigNumber;
          6: number;
          7: string;
          8: string;
          9: string;
          10: string;
          11: number;
          12: number;
        },
        {
          configuration: { data: BigNumber; 0: BigNumber };
          liquidityIndex: BigNumber;
          variableBorrowIndex: BigNumber;
          currentLiquidityRate: BigNumber;
          currentVariableBorrowRate: BigNumber;
          currentStableBorrowRate: BigNumber;
          lastUpdateTimestamp: number;
          aTokenAddress: string;
          stableDebtTokenAddress: string;
          variableDebtTokenAddress: string;
          interestRateStrategyAddress: string;
          id: number;
          tranche: number;
          0: { data: BigNumber; 0: BigNumber };
          1: BigNumber;
          2: BigNumber;
          3: BigNumber;
          4: BigNumber;
          5: BigNumber;
          6: number;
          7: string;
          8: string;
          9: string;
          10: string;
          11: number;
          12: number;
        }
      ];
    }>;

    "getType()"(overrides?: CallOverrides): Promise<{
      0: [
        {
          configuration: { data: BigNumber; 0: BigNumber };
          liquidityIndex: BigNumber;
          variableBorrowIndex: BigNumber;
          currentLiquidityRate: BigNumber;
          currentVariableBorrowRate: BigNumber;
          currentStableBorrowRate: BigNumber;
          lastUpdateTimestamp: number;
          aTokenAddress: string;
          stableDebtTokenAddress: string;
          variableDebtTokenAddress: string;
          interestRateStrategyAddress: string;
          id: number;
          tranche: number;
          0: { data: BigNumber; 0: BigNumber };
          1: BigNumber;
          2: BigNumber;
          3: BigNumber;
          4: BigNumber;
          5: BigNumber;
          6: number;
          7: string;
          8: string;
          9: string;
          10: string;
          11: number;
          12: number;
        },
        {
          configuration: { data: BigNumber; 0: BigNumber };
          liquidityIndex: BigNumber;
          variableBorrowIndex: BigNumber;
          currentLiquidityRate: BigNumber;
          currentVariableBorrowRate: BigNumber;
          currentStableBorrowRate: BigNumber;
          lastUpdateTimestamp: number;
          aTokenAddress: string;
          stableDebtTokenAddress: string;
          variableDebtTokenAddress: string;
          interestRateStrategyAddress: string;
          id: number;
          tranche: number;
          0: { data: BigNumber; 0: BigNumber };
          1: BigNumber;
          2: BigNumber;
          3: BigNumber;
          4: BigNumber;
          5: BigNumber;
          6: number;
          7: string;
          8: string;
          9: string;
          10: string;
          11: number;
          12: number;
        },
        {
          configuration: { data: BigNumber; 0: BigNumber };
          liquidityIndex: BigNumber;
          variableBorrowIndex: BigNumber;
          currentLiquidityRate: BigNumber;
          currentVariableBorrowRate: BigNumber;
          currentStableBorrowRate: BigNumber;
          lastUpdateTimestamp: number;
          aTokenAddress: string;
          stableDebtTokenAddress: string;
          variableDebtTokenAddress: string;
          interestRateStrategyAddress: string;
          id: number;
          tranche: number;
          0: { data: BigNumber; 0: BigNumber };
          1: BigNumber;
          2: BigNumber;
          3: BigNumber;
          4: BigNumber;
          5: BigNumber;
          6: number;
          7: string;
          8: string;
          9: string;
          10: string;
          11: number;
          12: number;
        }
      ];
    }>;
  };

  getType(
    overrides?: CallOverrides
  ): Promise<
    [
      {
        configuration: { data: BigNumber; 0: BigNumber };
        liquidityIndex: BigNumber;
        variableBorrowIndex: BigNumber;
        currentLiquidityRate: BigNumber;
        currentVariableBorrowRate: BigNumber;
        currentStableBorrowRate: BigNumber;
        lastUpdateTimestamp: number;
        aTokenAddress: string;
        stableDebtTokenAddress: string;
        variableDebtTokenAddress: string;
        interestRateStrategyAddress: string;
        id: number;
        tranche: number;
        0: { data: BigNumber; 0: BigNumber };
        1: BigNumber;
        2: BigNumber;
        3: BigNumber;
        4: BigNumber;
        5: BigNumber;
        6: number;
        7: string;
        8: string;
        9: string;
        10: string;
        11: number;
        12: number;
      },
      {
        configuration: { data: BigNumber; 0: BigNumber };
        liquidityIndex: BigNumber;
        variableBorrowIndex: BigNumber;
        currentLiquidityRate: BigNumber;
        currentVariableBorrowRate: BigNumber;
        currentStableBorrowRate: BigNumber;
        lastUpdateTimestamp: number;
        aTokenAddress: string;
        stableDebtTokenAddress: string;
        variableDebtTokenAddress: string;
        interestRateStrategyAddress: string;
        id: number;
        tranche: number;
        0: { data: BigNumber; 0: BigNumber };
        1: BigNumber;
        2: BigNumber;
        3: BigNumber;
        4: BigNumber;
        5: BigNumber;
        6: number;
        7: string;
        8: string;
        9: string;
        10: string;
        11: number;
        12: number;
      },
      {
        configuration: { data: BigNumber; 0: BigNumber };
        liquidityIndex: BigNumber;
        variableBorrowIndex: BigNumber;
        currentLiquidityRate: BigNumber;
        currentVariableBorrowRate: BigNumber;
        currentStableBorrowRate: BigNumber;
        lastUpdateTimestamp: number;
        aTokenAddress: string;
        stableDebtTokenAddress: string;
        variableDebtTokenAddress: string;
        interestRateStrategyAddress: string;
        id: number;
        tranche: number;
        0: { data: BigNumber; 0: BigNumber };
        1: BigNumber;
        2: BigNumber;
        3: BigNumber;
        4: BigNumber;
        5: BigNumber;
        6: number;
        7: string;
        8: string;
        9: string;
        10: string;
        11: number;
        12: number;
      }
    ]
  >;

  "getType()"(
    overrides?: CallOverrides
  ): Promise<
    [
      {
        configuration: { data: BigNumber; 0: BigNumber };
        liquidityIndex: BigNumber;
        variableBorrowIndex: BigNumber;
        currentLiquidityRate: BigNumber;
        currentVariableBorrowRate: BigNumber;
        currentStableBorrowRate: BigNumber;
        lastUpdateTimestamp: number;
        aTokenAddress: string;
        stableDebtTokenAddress: string;
        variableDebtTokenAddress: string;
        interestRateStrategyAddress: string;
        id: number;
        tranche: number;
        0: { data: BigNumber; 0: BigNumber };
        1: BigNumber;
        2: BigNumber;
        3: BigNumber;
        4: BigNumber;
        5: BigNumber;
        6: number;
        7: string;
        8: string;
        9: string;
        10: string;
        11: number;
        12: number;
      },
      {
        configuration: { data: BigNumber; 0: BigNumber };
        liquidityIndex: BigNumber;
        variableBorrowIndex: BigNumber;
        currentLiquidityRate: BigNumber;
        currentVariableBorrowRate: BigNumber;
        currentStableBorrowRate: BigNumber;
        lastUpdateTimestamp: number;
        aTokenAddress: string;
        stableDebtTokenAddress: string;
        variableDebtTokenAddress: string;
        interestRateStrategyAddress: string;
        id: number;
        tranche: number;
        0: { data: BigNumber; 0: BigNumber };
        1: BigNumber;
        2: BigNumber;
        3: BigNumber;
        4: BigNumber;
        5: BigNumber;
        6: number;
        7: string;
        8: string;
        9: string;
        10: string;
        11: number;
        12: number;
      },
      {
        configuration: { data: BigNumber; 0: BigNumber };
        liquidityIndex: BigNumber;
        variableBorrowIndex: BigNumber;
        currentLiquidityRate: BigNumber;
        currentVariableBorrowRate: BigNumber;
        currentStableBorrowRate: BigNumber;
        lastUpdateTimestamp: number;
        aTokenAddress: string;
        stableDebtTokenAddress: string;
        variableDebtTokenAddress: string;
        interestRateStrategyAddress: string;
        id: number;
        tranche: number;
        0: { data: BigNumber; 0: BigNumber };
        1: BigNumber;
        2: BigNumber;
        3: BigNumber;
        4: BigNumber;
        5: BigNumber;
        6: number;
        7: string;
        8: string;
        9: string;
        10: string;
        11: number;
        12: number;
      }
    ]
  >;

  callStatic: {
    getType(
      overrides?: CallOverrides
    ): Promise<
      [
        {
          configuration: { data: BigNumber; 0: BigNumber };
          liquidityIndex: BigNumber;
          variableBorrowIndex: BigNumber;
          currentLiquidityRate: BigNumber;
          currentVariableBorrowRate: BigNumber;
          currentStableBorrowRate: BigNumber;
          lastUpdateTimestamp: number;
          aTokenAddress: string;
          stableDebtTokenAddress: string;
          variableDebtTokenAddress: string;
          interestRateStrategyAddress: string;
          id: number;
          tranche: number;
          0: { data: BigNumber; 0: BigNumber };
          1: BigNumber;
          2: BigNumber;
          3: BigNumber;
          4: BigNumber;
          5: BigNumber;
          6: number;
          7: string;
          8: string;
          9: string;
          10: string;
          11: number;
          12: number;
        },
        {
          configuration: { data: BigNumber; 0: BigNumber };
          liquidityIndex: BigNumber;
          variableBorrowIndex: BigNumber;
          currentLiquidityRate: BigNumber;
          currentVariableBorrowRate: BigNumber;
          currentStableBorrowRate: BigNumber;
          lastUpdateTimestamp: number;
          aTokenAddress: string;
          stableDebtTokenAddress: string;
          variableDebtTokenAddress: string;
          interestRateStrategyAddress: string;
          id: number;
          tranche: number;
          0: { data: BigNumber; 0: BigNumber };
          1: BigNumber;
          2: BigNumber;
          3: BigNumber;
          4: BigNumber;
          5: BigNumber;
          6: number;
          7: string;
          8: string;
          9: string;
          10: string;
          11: number;
          12: number;
        },
        {
          configuration: { data: BigNumber; 0: BigNumber };
          liquidityIndex: BigNumber;
          variableBorrowIndex: BigNumber;
          currentLiquidityRate: BigNumber;
          currentVariableBorrowRate: BigNumber;
          currentStableBorrowRate: BigNumber;
          lastUpdateTimestamp: number;
          aTokenAddress: string;
          stableDebtTokenAddress: string;
          variableDebtTokenAddress: string;
          interestRateStrategyAddress: string;
          id: number;
          tranche: number;
          0: { data: BigNumber; 0: BigNumber };
          1: BigNumber;
          2: BigNumber;
          3: BigNumber;
          4: BigNumber;
          5: BigNumber;
          6: number;
          7: string;
          8: string;
          9: string;
          10: string;
          11: number;
          12: number;
        }
      ]
    >;

    "getType()"(
      overrides?: CallOverrides
    ): Promise<
      [
        {
          configuration: { data: BigNumber; 0: BigNumber };
          liquidityIndex: BigNumber;
          variableBorrowIndex: BigNumber;
          currentLiquidityRate: BigNumber;
          currentVariableBorrowRate: BigNumber;
          currentStableBorrowRate: BigNumber;
          lastUpdateTimestamp: number;
          aTokenAddress: string;
          stableDebtTokenAddress: string;
          variableDebtTokenAddress: string;
          interestRateStrategyAddress: string;
          id: number;
          tranche: number;
          0: { data: BigNumber; 0: BigNumber };
          1: BigNumber;
          2: BigNumber;
          3: BigNumber;
          4: BigNumber;
          5: BigNumber;
          6: number;
          7: string;
          8: string;
          9: string;
          10: string;
          11: number;
          12: number;
        },
        {
          configuration: { data: BigNumber; 0: BigNumber };
          liquidityIndex: BigNumber;
          variableBorrowIndex: BigNumber;
          currentLiquidityRate: BigNumber;
          currentVariableBorrowRate: BigNumber;
          currentStableBorrowRate: BigNumber;
          lastUpdateTimestamp: number;
          aTokenAddress: string;
          stableDebtTokenAddress: string;
          variableDebtTokenAddress: string;
          interestRateStrategyAddress: string;
          id: number;
          tranche: number;
          0: { data: BigNumber; 0: BigNumber };
          1: BigNumber;
          2: BigNumber;
          3: BigNumber;
          4: BigNumber;
          5: BigNumber;
          6: number;
          7: string;
          8: string;
          9: string;
          10: string;
          11: number;
          12: number;
        },
        {
          configuration: { data: BigNumber; 0: BigNumber };
          liquidityIndex: BigNumber;
          variableBorrowIndex: BigNumber;
          currentLiquidityRate: BigNumber;
          currentVariableBorrowRate: BigNumber;
          currentStableBorrowRate: BigNumber;
          lastUpdateTimestamp: number;
          aTokenAddress: string;
          stableDebtTokenAddress: string;
          variableDebtTokenAddress: string;
          interestRateStrategyAddress: string;
          id: number;
          tranche: number;
          0: { data: BigNumber; 0: BigNumber };
          1: BigNumber;
          2: BigNumber;
          3: BigNumber;
          4: BigNumber;
          5: BigNumber;
          6: number;
          7: string;
          8: string;
          9: string;
          10: string;
          11: number;
          12: number;
        }
      ]
    >;
  };

  filters: {};

  estimateGas: {
    getType(overrides?: CallOverrides): Promise<BigNumber>;

    "getType()"(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    getType(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "getType()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
