"use strict";
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
Object.defineProperty(exports, "__esModule", { value: true });
exports.ICurveLiquidityRewardGaugeFactory = void 0;
const ethers_1 = require("ethers");
class ICurveLiquidityRewardGaugeFactory {
    static connect(address, signerOrProvider) {
        return new ethers_1.Contract(address, _abi, signerOrProvider);
    }
}
exports.ICurveLiquidityRewardGaugeFactory = ICurveLiquidityRewardGaugeFactory;
const _abi = [
    {
        inputs: [],
        name: "rewarded_token",
        outputs: [
            {
                internalType: "address",
                name: "",
                type: "address",
            },
        ],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [
            {
                internalType: "address",
                name: "arg0",
                type: "address",
            },
        ],
        name: "rewards_for",
        outputs: [
            {
                internalType: "uint256",
                name: "",
                type: "uint256",
            },
        ],
        stateMutability: "view",
        type: "function",
    },
];
//# sourceMappingURL=ICurveLiquidityRewardGaugeFactory.js.map