"use strict";
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
Object.defineProperty(exports, "__esModule", { value: true });
exports.ICurveAddressProviderFactory = void 0;
const ethers_1 = require("ethers");
class ICurveAddressProviderFactory {
    static connect(address, signerOrProvider) {
        return new ethers_1.Contract(address, _abi, signerOrProvider);
    }
}
exports.ICurveAddressProviderFactory = ICurveAddressProviderFactory;
const _abi = [
    {
        inputs: [],
        name: "get_registry",
        outputs: [
            {
                internalType: "address",
                name: "",
                type: "address",
            },
        ],
        stateMutability: "view",
        type: "function",
    },
];
//# sourceMappingURL=ICurveAddressProviderFactory.js.map