"use strict";
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
Object.defineProperty(exports, "__esModule", { value: true });
exports.IInitializableDebtTokenFactory = void 0;
const ethers_1 = require("ethers");
class IInitializableDebtTokenFactory {
    static connect(address, signerOrProvider) {
        return new ethers_1.Contract(address, _abi, signerOrProvider);
    }
}
exports.IInitializableDebtTokenFactory = IInitializableDebtTokenFactory;
const _abi = [
    {
        anonymous: false,
        inputs: [
            {
                indexed: true,
                internalType: "address",
                name: "underlyingAsset",
                type: "address",
            },
            {
                indexed: true,
                internalType: "address",
                name: "pool",
                type: "address",
            },
            {
                indexed: false,
                internalType: "address",
                name: "incentivesController",
                type: "address",
            },
            {
                indexed: false,
                internalType: "uint8",
                name: "debtTokenDecimals",
                type: "uint8",
            },
            {
                indexed: false,
                internalType: "string",
                name: "debtTokenName",
                type: "string",
            },
            {
                indexed: false,
                internalType: "string",
                name: "debtTokenSymbol",
                type: "string",
            },
            {
                indexed: false,
                internalType: "bytes",
                name: "params",
                type: "bytes",
            },
        ],
        name: "Initialized",
        type: "event",
    },
    {
        inputs: [
            {
                internalType: "contract ILendingPool",
                name: "pool",
                type: "address",
            },
            {
                internalType: "address",
                name: "underlyingAsset",
                type: "address",
            },
            {
                internalType: "uint64",
                name: "trancheId",
                type: "uint64",
            },
            {
                internalType: "contract IAaveIncentivesController",
                name: "incentivesController",
                type: "address",
            },
            {
                internalType: "uint8",
                name: "debtTokenDecimals",
                type: "uint8",
            },
            {
                internalType: "string",
                name: "debtTokenName",
                type: "string",
            },
            {
                internalType: "string",
                name: "debtTokenSymbol",
                type: "string",
            },
            {
                internalType: "bytes",
                name: "params",
                type: "bytes",
            },
        ],
        name: "initialize",
        outputs: [],
        stateMutability: "nonpayable",
        type: "function",
    },
];
//# sourceMappingURL=IInitializableDebtTokenFactory.js.map