"use strict";
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
Object.defineProperty(exports, "__esModule", { value: true });
exports.IParaSwapAugustusRegistryFactory = void 0;
const ethers_1 = require("ethers");
class IParaSwapAugustusRegistryFactory {
    static connect(address, signerOrProvider) {
        return new ethers_1.Contract(address, _abi, signerOrProvider);
    }
}
exports.IParaSwapAugustusRegistryFactory = IParaSwapAugustusRegistryFactory;
const _abi = [
    {
        inputs: [
            {
                internalType: "address",
                name: "augustus",
                type: "address",
            },
        ],
        name: "isValidAugustus",
        outputs: [
            {
                internalType: "bool",
                name: "",
                type: "bool",
            },
        ],
        stateMutability: "view",
        type: "function",
    },
];
//# sourceMappingURL=IParaSwapAugustusRegistryFactory.js.map