"use strict";
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
Object.defineProperty(exports, "__esModule", { value: true });
exports.IUniswapExchangeFactory = void 0;
const ethers_1 = require("ethers");
class IUniswapExchangeFactory {
    static connect(address, signerOrProvider) {
        return new ethers_1.Contract(address, _abi, signerOrProvider);
    }
}
exports.IUniswapExchangeFactory = IUniswapExchangeFactory;
const _abi = [
    {
        anonymous: false,
        inputs: [
            {
                indexed: true,
                internalType: "address",
                name: "provider",
                type: "address",
            },
            {
                indexed: true,
                internalType: "uint256",
                name: "eth_amount",
                type: "uint256",
            },
            {
                indexed: true,
                internalType: "uint256",
                name: "token_amount",
                type: "uint256",
            },
        ],
        name: "AddLiquidity",
        type: "event",
    },
    {
        anonymous: false,
        inputs: [
            {
                indexed: true,
                internalType: "address",
                name: "buyer",
                type: "address",
            },
            {
                indexed: true,
                internalType: "uint256",
                name: "tokens_sold",
                type: "uint256",
            },
            {
                indexed: true,
                internalType: "uint256",
                name: "eth_bought",
                type: "uint256",
            },
        ],
        name: "EthPurchase",
        type: "event",
    },
    {
        anonymous: false,
        inputs: [
            {
                indexed: true,
                internalType: "address",
                name: "provider",
                type: "address",
            },
            {
                indexed: true,
                internalType: "uint256",
                name: "eth_amount",
                type: "uint256",
            },
            {
                indexed: true,
                internalType: "uint256",
                name: "token_amount",
                type: "uint256",
            },
        ],
        name: "RemoveLiquidity",
        type: "event",
    },
    {
        anonymous: false,
        inputs: [
            {
                indexed: true,
                internalType: "address",
                name: "buyer",
                type: "address",
            },
            {
                indexed: true,
                internalType: "uint256",
                name: "eth_sold",
                type: "uint256",
            },
            {
                indexed: true,
                internalType: "uint256",
                name: "tokens_bought",
                type: "uint256",
            },
        ],
        name: "TokenPurchase",
        type: "event",
    },
];
//# sourceMappingURL=IUniswapExchangeFactory.js.map