/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface ATokensAndRatesHelperInterface extends ethers.utils.Interface {
  functions: {
    "configureReserves(tuple[],uint64)": FunctionFragment;
    "freezeReserve(address,uint64)": FunctionFragment;
    "initDeployment(tuple[])": FunctionFragment;
    "owner()": FunctionFragment;
    "renounceOwnership()": FunctionFragment;
    "setReserveFactor(address,uint64,uint256)": FunctionFragment;
    "setVMEXReserveFactor(address,uint64,uint256)": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
    "unfreezeReserve(address,uint64)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "configureReserves",
    values: [
      {
        asset: string;
        baseLTV: BigNumberish;
        liquidationThreshold: BigNumberish;
        liquidationBonus: BigNumberish;
        reserveFactor: BigNumberish;
        stableBorrowingEnabled: boolean;
        borrowingEnabled: boolean;
      }[],
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "freezeReserve",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "initDeployment",
    values: [
      {
        asset: string;
        rates: [
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish
        ];
      }[]
    ]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setReserveFactor",
    values: [string, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setVMEXReserveFactor",
    values: [string, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "unfreezeReserve",
    values: [string, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "configureReserves",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "freezeReserve",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "initDeployment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setReserveFactor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setVMEXReserveFactor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "unfreezeReserve",
    data: BytesLike
  ): Result;

  events: {
    "OwnershipTransferred(address,address)": EventFragment;
    "ReserveFactorChanged(address,uint256)": EventFragment;
    "ReserveFrozen(address)": EventFragment;
    "ReserveUnfrozen(address)": EventFragment;
    "deployedContracts(address,address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ReserveFactorChanged"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ReserveFrozen"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ReserveUnfrozen"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "deployedContracts"): EventFragment;
}

export class ATokensAndRatesHelper extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: ATokensAndRatesHelperInterface;

  functions: {
    configureReserves(
      inputParams: {
        asset: string;
        baseLTV: BigNumberish;
        liquidationThreshold: BigNumberish;
        liquidationBonus: BigNumberish;
        reserveFactor: BigNumberish;
        stableBorrowingEnabled: boolean;
        borrowingEnabled: boolean;
      }[],
      trancheId: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "configureReserves(tuple[],uint64)"(
      inputParams: {
        asset: string;
        baseLTV: BigNumberish;
        liquidationThreshold: BigNumberish;
        liquidationBonus: BigNumberish;
        reserveFactor: BigNumberish;
        stableBorrowingEnabled: boolean;
        borrowingEnabled: boolean;
      }[],
      trancheId: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    freezeReserve(
      asset: string,
      trancheId: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "freezeReserve(address,uint64)"(
      asset: string,
      trancheId: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    initDeployment(
      inputParams: {
        asset: string;
        rates: [
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish
        ];
      }[],
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "initDeployment(tuple[])"(
      inputParams: {
        asset: string;
        rates: [
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish
        ];
      }[],
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    owner(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    "owner()"(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    renounceOwnership(overrides?: Overrides): Promise<ContractTransaction>;

    "renounceOwnership()"(overrides?: Overrides): Promise<ContractTransaction>;

    setReserveFactor(
      asset: string,
      trancheId: BigNumberish,
      reserveFactor: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "setReserveFactor(address,uint64,uint256)"(
      asset: string,
      trancheId: BigNumberish,
      reserveFactor: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    setVMEXReserveFactor(
      asset: string,
      trancheId: BigNumberish,
      reserveFactor: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "setVMEXReserveFactor(address,uint64,uint256)"(
      asset: string,
      trancheId: BigNumberish,
      reserveFactor: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "transferOwnership(address)"(
      newOwner: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    unfreezeReserve(
      asset: string,
      trancheId: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "unfreezeReserve(address,uint64)"(
      asset: string,
      trancheId: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;
  };

  configureReserves(
    inputParams: {
      asset: string;
      baseLTV: BigNumberish;
      liquidationThreshold: BigNumberish;
      liquidationBonus: BigNumberish;
      reserveFactor: BigNumberish;
      stableBorrowingEnabled: boolean;
      borrowingEnabled: boolean;
    }[],
    trancheId: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "configureReserves(tuple[],uint64)"(
    inputParams: {
      asset: string;
      baseLTV: BigNumberish;
      liquidationThreshold: BigNumberish;
      liquidationBonus: BigNumberish;
      reserveFactor: BigNumberish;
      stableBorrowingEnabled: boolean;
      borrowingEnabled: boolean;
    }[],
    trancheId: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  freezeReserve(
    asset: string,
    trancheId: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "freezeReserve(address,uint64)"(
    asset: string,
    trancheId: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  initDeployment(
    inputParams: {
      asset: string;
      rates: [
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish
      ];
    }[],
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "initDeployment(tuple[])"(
    inputParams: {
      asset: string;
      rates: [
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish
      ];
    }[],
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  owner(overrides?: CallOverrides): Promise<string>;

  "owner()"(overrides?: CallOverrides): Promise<string>;

  renounceOwnership(overrides?: Overrides): Promise<ContractTransaction>;

  "renounceOwnership()"(overrides?: Overrides): Promise<ContractTransaction>;

  setReserveFactor(
    asset: string,
    trancheId: BigNumberish,
    reserveFactor: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "setReserveFactor(address,uint64,uint256)"(
    asset: string,
    trancheId: BigNumberish,
    reserveFactor: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  setVMEXReserveFactor(
    asset: string,
    trancheId: BigNumberish,
    reserveFactor: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "setVMEXReserveFactor(address,uint64,uint256)"(
    asset: string,
    trancheId: BigNumberish,
    reserveFactor: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  transferOwnership(
    newOwner: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "transferOwnership(address)"(
    newOwner: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  unfreezeReserve(
    asset: string,
    trancheId: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "unfreezeReserve(address,uint64)"(
    asset: string,
    trancheId: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  callStatic: {
    configureReserves(
      inputParams: {
        asset: string;
        baseLTV: BigNumberish;
        liquidationThreshold: BigNumberish;
        liquidationBonus: BigNumberish;
        reserveFactor: BigNumberish;
        stableBorrowingEnabled: boolean;
        borrowingEnabled: boolean;
      }[],
      trancheId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "configureReserves(tuple[],uint64)"(
      inputParams: {
        asset: string;
        baseLTV: BigNumberish;
        liquidationThreshold: BigNumberish;
        liquidationBonus: BigNumberish;
        reserveFactor: BigNumberish;
        stableBorrowingEnabled: boolean;
        borrowingEnabled: boolean;
      }[],
      trancheId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    freezeReserve(
      asset: string,
      trancheId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "freezeReserve(address,uint64)"(
      asset: string,
      trancheId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    initDeployment(
      inputParams: {
        asset: string;
        rates: [
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish
        ];
      }[],
      overrides?: CallOverrides
    ): Promise<void>;

    "initDeployment(tuple[])"(
      inputParams: {
        asset: string;
        rates: [
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish
        ];
      }[],
      overrides?: CallOverrides
    ): Promise<void>;

    owner(overrides?: CallOverrides): Promise<string>;

    "owner()"(overrides?: CallOverrides): Promise<string>;

    renounceOwnership(overrides?: CallOverrides): Promise<void>;

    "renounceOwnership()"(overrides?: CallOverrides): Promise<void>;

    setReserveFactor(
      asset: string,
      trancheId: BigNumberish,
      reserveFactor: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "setReserveFactor(address,uint64,uint256)"(
      asset: string,
      trancheId: BigNumberish,
      reserveFactor: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    setVMEXReserveFactor(
      asset: string,
      trancheId: BigNumberish,
      reserveFactor: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "setVMEXReserveFactor(address,uint64,uint256)"(
      asset: string,
      trancheId: BigNumberish,
      reserveFactor: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    transferOwnership(
      newOwner: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "transferOwnership(address)"(
      newOwner: string,
      overrides?: CallOverrides
    ): Promise<void>;

    unfreezeReserve(
      asset: string,
      trancheId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "unfreezeReserve(address,uint64)"(
      asset: string,
      trancheId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    OwnershipTransferred(
      previousOwner: string | null,
      newOwner: string | null
    ): EventFilter;

    ReserveFactorChanged(asset: string | null, factor: null): EventFilter;

    ReserveFrozen(asset: string | null): EventFilter;

    ReserveUnfrozen(asset: string | null): EventFilter;

    deployedContracts(aToken: null, strategy: null): EventFilter;
  };

  estimateGas: {
    configureReserves(
      inputParams: {
        asset: string;
        baseLTV: BigNumberish;
        liquidationThreshold: BigNumberish;
        liquidationBonus: BigNumberish;
        reserveFactor: BigNumberish;
        stableBorrowingEnabled: boolean;
        borrowingEnabled: boolean;
      }[],
      trancheId: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "configureReserves(tuple[],uint64)"(
      inputParams: {
        asset: string;
        baseLTV: BigNumberish;
        liquidationThreshold: BigNumberish;
        liquidationBonus: BigNumberish;
        reserveFactor: BigNumberish;
        stableBorrowingEnabled: boolean;
        borrowingEnabled: boolean;
      }[],
      trancheId: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    freezeReserve(
      asset: string,
      trancheId: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "freezeReserve(address,uint64)"(
      asset: string,
      trancheId: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    initDeployment(
      inputParams: {
        asset: string;
        rates: [
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish
        ];
      }[],
      overrides?: Overrides
    ): Promise<BigNumber>;

    "initDeployment(tuple[])"(
      inputParams: {
        asset: string;
        rates: [
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish
        ];
      }[],
      overrides?: Overrides
    ): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    "owner()"(overrides?: CallOverrides): Promise<BigNumber>;

    renounceOwnership(overrides?: Overrides): Promise<BigNumber>;

    "renounceOwnership()"(overrides?: Overrides): Promise<BigNumber>;

    setReserveFactor(
      asset: string,
      trancheId: BigNumberish,
      reserveFactor: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "setReserveFactor(address,uint64,uint256)"(
      asset: string,
      trancheId: BigNumberish,
      reserveFactor: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    setVMEXReserveFactor(
      asset: string,
      trancheId: BigNumberish,
      reserveFactor: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "setVMEXReserveFactor(address,uint64,uint256)"(
      asset: string,
      trancheId: BigNumberish,
      reserveFactor: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "transferOwnership(address)"(
      newOwner: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    unfreezeReserve(
      asset: string,
      trancheId: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "unfreezeReserve(address,uint64)"(
      asset: string,
      trancheId: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    configureReserves(
      inputParams: {
        asset: string;
        baseLTV: BigNumberish;
        liquidationThreshold: BigNumberish;
        liquidationBonus: BigNumberish;
        reserveFactor: BigNumberish;
        stableBorrowingEnabled: boolean;
        borrowingEnabled: boolean;
      }[],
      trancheId: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "configureReserves(tuple[],uint64)"(
      inputParams: {
        asset: string;
        baseLTV: BigNumberish;
        liquidationThreshold: BigNumberish;
        liquidationBonus: BigNumberish;
        reserveFactor: BigNumberish;
        stableBorrowingEnabled: boolean;
        borrowingEnabled: boolean;
      }[],
      trancheId: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    freezeReserve(
      asset: string,
      trancheId: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "freezeReserve(address,uint64)"(
      asset: string,
      trancheId: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    initDeployment(
      inputParams: {
        asset: string;
        rates: [
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish
        ];
      }[],
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "initDeployment(tuple[])"(
      inputParams: {
        asset: string;
        rates: [
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish
        ];
      }[],
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "owner()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    renounceOwnership(overrides?: Overrides): Promise<PopulatedTransaction>;

    "renounceOwnership()"(overrides?: Overrides): Promise<PopulatedTransaction>;

    setReserveFactor(
      asset: string,
      trancheId: BigNumberish,
      reserveFactor: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "setReserveFactor(address,uint64,uint256)"(
      asset: string,
      trancheId: BigNumberish,
      reserveFactor: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    setVMEXReserveFactor(
      asset: string,
      trancheId: BigNumberish,
      reserveFactor: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "setVMEXReserveFactor(address,uint64,uint256)"(
      asset: string,
      trancheId: BigNumberish,
      reserveFactor: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "transferOwnership(address)"(
      newOwner: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    unfreezeReserve(
      asset: string,
      trancheId: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "unfreezeReserve(address,uint64)"(
      asset: string,
      trancheId: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;
  };
}
