/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface ConvexOracleInterface extends ethers.utils.Interface {
  functions: {
    "get_convex_price(address,uint256[],uint16,address,address)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "get_convex_price",
    values: [string, BigNumberish[], BigNumberish, string, string]
  ): string;

  decodeFunctionResult(
    functionFragment: "get_convex_price",
    data: BytesLike
  ): Result;

  events: {};
}

export class ConvexOracle extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: ConvexOracleInterface;

  functions: {
    get_convex_price(
      curve_pool: string,
      prices: BigNumberish[],
      pid: BigNumberish,
      convex_lp: string,
      curve_lp: string,
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;

    "get_convex_price(address,uint256[],uint16,address,address)"(
      curve_pool: string,
      prices: BigNumberish[],
      pid: BigNumberish,
      convex_lp: string,
      curve_lp: string,
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;
  };

  get_convex_price(
    curve_pool: string,
    prices: BigNumberish[],
    pid: BigNumberish,
    convex_lp: string,
    curve_lp: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  "get_convex_price(address,uint256[],uint16,address,address)"(
    curve_pool: string,
    prices: BigNumberish[],
    pid: BigNumberish,
    convex_lp: string,
    curve_lp: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  callStatic: {
    get_convex_price(
      curve_pool: string,
      prices: BigNumberish[],
      pid: BigNumberish,
      convex_lp: string,
      curve_lp: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "get_convex_price(address,uint256[],uint16,address,address)"(
      curve_pool: string,
      prices: BigNumberish[],
      pid: BigNumberish,
      convex_lp: string,
      curve_lp: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  filters: {};

  estimateGas: {
    get_convex_price(
      curve_pool: string,
      prices: BigNumberish[],
      pid: BigNumberish,
      convex_lp: string,
      curve_lp: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "get_convex_price(address,uint256[],uint16,address,address)"(
      curve_pool: string,
      prices: BigNumberish[],
      pid: BigNumberish,
      convex_lp: string,
      curve_lp: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    get_convex_price(
      curve_pool: string,
      prices: BigNumberish[],
      pid: BigNumberish,
      convex_lp: string,
      curve_lp: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "get_convex_price(address,uint256[],uint16,address,address)"(
      curve_pool: string,
      prices: BigNumberish[],
      pid: BigNumberish,
      convex_lp: string,
      curve_lp: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
