/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface ICurveZapInterface extends ethers.utils.Interface {
  functions: {
    "add_liquidity(uint256[2],uint256)": FunctionFragment;
    "calc_withdraw_one_coin(uint256,int128)": FunctionFragment;
    "coins(int128)": FunctionFragment;
    "curve()": FunctionFragment;
    "remove_liquidity(uint256,uint256[2])": FunctionFragment;
    "remove_liquidity_imbalance(uint256[2],uint256)": FunctionFragment;
    "remove_liquidity_one_coin(uint256,int128,uint256)": FunctionFragment;
    "token()": FunctionFragment;
    "underlying_coins(int128)": FunctionFragment;
    "withdraw_donated_dust()": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "add_liquidity",
    values: [[BigNumberish, BigNumberish], BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "calc_withdraw_one_coin",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "coins", values: [BigNumberish]): string;
  encodeFunctionData(functionFragment: "curve", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "remove_liquidity",
    values: [BigNumberish, [BigNumberish, BigNumberish]]
  ): string;
  encodeFunctionData(
    functionFragment: "remove_liquidity_imbalance",
    values: [[BigNumberish, BigNumberish], BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "remove_liquidity_one_coin",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "token", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "underlying_coins",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "withdraw_donated_dust",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "add_liquidity",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "calc_withdraw_one_coin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "coins", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "curve", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "remove_liquidity",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "remove_liquidity_imbalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "remove_liquidity_one_coin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "token", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "underlying_coins",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdraw_donated_dust",
    data: BytesLike
  ): Result;

  events: {};
}

export class ICurveZap extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: ICurveZapInterface;

  functions: {
    add_liquidity(
      uamounts: [BigNumberish, BigNumberish],
      min_mint_amount: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "add_liquidity(uint256[2],uint256)"(
      uamounts: [BigNumberish, BigNumberish],
      min_mint_amount: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    calc_withdraw_one_coin(
      _token_amount: BigNumberish,
      i: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "calc_withdraw_one_coin(uint256,int128)"(
      _token_amount: BigNumberish,
      i: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    coins(
      arg0: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "coins(int128)"(
      arg0: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    curve(overrides?: Overrides): Promise<ContractTransaction>;

    "curve()"(overrides?: Overrides): Promise<ContractTransaction>;

    remove_liquidity(
      _amount: BigNumberish,
      min_uamounts: [BigNumberish, BigNumberish],
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "remove_liquidity(uint256,uint256[2])"(
      _amount: BigNumberish,
      min_uamounts: [BigNumberish, BigNumberish],
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    remove_liquidity_imbalance(
      uamounts: [BigNumberish, BigNumberish],
      max_burn_amount: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "remove_liquidity_imbalance(uint256[2],uint256)"(
      uamounts: [BigNumberish, BigNumberish],
      max_burn_amount: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "remove_liquidity_one_coin(uint256,int128,uint256)"(
      _token_amount: BigNumberish,
      i: BigNumberish,
      min_uamount: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "remove_liquidity_one_coin(uint256,int128,uint256,bool)"(
      _token_amount: BigNumberish,
      i: BigNumberish,
      min_uamount: BigNumberish,
      donate_dust: boolean,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    token(overrides?: Overrides): Promise<ContractTransaction>;

    "token()"(overrides?: Overrides): Promise<ContractTransaction>;

    underlying_coins(
      arg0: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "underlying_coins(int128)"(
      arg0: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    withdraw_donated_dust(overrides?: Overrides): Promise<ContractTransaction>;

    "withdraw_donated_dust()"(
      overrides?: Overrides
    ): Promise<ContractTransaction>;
  };

  add_liquidity(
    uamounts: [BigNumberish, BigNumberish],
    min_mint_amount: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "add_liquidity(uint256[2],uint256)"(
    uamounts: [BigNumberish, BigNumberish],
    min_mint_amount: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  calc_withdraw_one_coin(
    _token_amount: BigNumberish,
    i: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "calc_withdraw_one_coin(uint256,int128)"(
    _token_amount: BigNumberish,
    i: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  coins(
    arg0: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "coins(int128)"(
    arg0: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  curve(overrides?: Overrides): Promise<ContractTransaction>;

  "curve()"(overrides?: Overrides): Promise<ContractTransaction>;

  remove_liquidity(
    _amount: BigNumberish,
    min_uamounts: [BigNumberish, BigNumberish],
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "remove_liquidity(uint256,uint256[2])"(
    _amount: BigNumberish,
    min_uamounts: [BigNumberish, BigNumberish],
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  remove_liquidity_imbalance(
    uamounts: [BigNumberish, BigNumberish],
    max_burn_amount: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "remove_liquidity_imbalance(uint256[2],uint256)"(
    uamounts: [BigNumberish, BigNumberish],
    max_burn_amount: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "remove_liquidity_one_coin(uint256,int128,uint256)"(
    _token_amount: BigNumberish,
    i: BigNumberish,
    min_uamount: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "remove_liquidity_one_coin(uint256,int128,uint256,bool)"(
    _token_amount: BigNumberish,
    i: BigNumberish,
    min_uamount: BigNumberish,
    donate_dust: boolean,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  token(overrides?: Overrides): Promise<ContractTransaction>;

  "token()"(overrides?: Overrides): Promise<ContractTransaction>;

  underlying_coins(
    arg0: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "underlying_coins(int128)"(
    arg0: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  withdraw_donated_dust(overrides?: Overrides): Promise<ContractTransaction>;

  "withdraw_donated_dust()"(
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  callStatic: {
    add_liquidity(
      uamounts: [BigNumberish, BigNumberish],
      min_mint_amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "add_liquidity(uint256[2],uint256)"(
      uamounts: [BigNumberish, BigNumberish],
      min_mint_amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    calc_withdraw_one_coin(
      _token_amount: BigNumberish,
      i: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "calc_withdraw_one_coin(uint256,int128)"(
      _token_amount: BigNumberish,
      i: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    coins(arg0: BigNumberish, overrides?: CallOverrides): Promise<string>;

    "coins(int128)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    curve(overrides?: CallOverrides): Promise<string>;

    "curve()"(overrides?: CallOverrides): Promise<string>;

    remove_liquidity(
      _amount: BigNumberish,
      min_uamounts: [BigNumberish, BigNumberish],
      overrides?: CallOverrides
    ): Promise<void>;

    "remove_liquidity(uint256,uint256[2])"(
      _amount: BigNumberish,
      min_uamounts: [BigNumberish, BigNumberish],
      overrides?: CallOverrides
    ): Promise<void>;

    remove_liquidity_imbalance(
      uamounts: [BigNumberish, BigNumberish],
      max_burn_amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "remove_liquidity_imbalance(uint256[2],uint256)"(
      uamounts: [BigNumberish, BigNumberish],
      max_burn_amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "remove_liquidity_one_coin(uint256,int128,uint256)"(
      _token_amount: BigNumberish,
      i: BigNumberish,
      min_uamount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "remove_liquidity_one_coin(uint256,int128,uint256,bool)"(
      _token_amount: BigNumberish,
      i: BigNumberish,
      min_uamount: BigNumberish,
      donate_dust: boolean,
      overrides?: CallOverrides
    ): Promise<void>;

    token(overrides?: CallOverrides): Promise<string>;

    "token()"(overrides?: CallOverrides): Promise<string>;

    underlying_coins(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    "underlying_coins(int128)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    withdraw_donated_dust(overrides?: CallOverrides): Promise<void>;

    "withdraw_donated_dust()"(overrides?: CallOverrides): Promise<void>;
  };

  filters: {};

  estimateGas: {
    add_liquidity(
      uamounts: [BigNumberish, BigNumberish],
      min_mint_amount: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "add_liquidity(uint256[2],uint256)"(
      uamounts: [BigNumberish, BigNumberish],
      min_mint_amount: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    calc_withdraw_one_coin(
      _token_amount: BigNumberish,
      i: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "calc_withdraw_one_coin(uint256,int128)"(
      _token_amount: BigNumberish,
      i: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    coins(arg0: BigNumberish, overrides?: Overrides): Promise<BigNumber>;

    "coins(int128)"(
      arg0: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    curve(overrides?: Overrides): Promise<BigNumber>;

    "curve()"(overrides?: Overrides): Promise<BigNumber>;

    remove_liquidity(
      _amount: BigNumberish,
      min_uamounts: [BigNumberish, BigNumberish],
      overrides?: Overrides
    ): Promise<BigNumber>;

    "remove_liquidity(uint256,uint256[2])"(
      _amount: BigNumberish,
      min_uamounts: [BigNumberish, BigNumberish],
      overrides?: Overrides
    ): Promise<BigNumber>;

    remove_liquidity_imbalance(
      uamounts: [BigNumberish, BigNumberish],
      max_burn_amount: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "remove_liquidity_imbalance(uint256[2],uint256)"(
      uamounts: [BigNumberish, BigNumberish],
      max_burn_amount: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "remove_liquidity_one_coin(uint256,int128,uint256)"(
      _token_amount: BigNumberish,
      i: BigNumberish,
      min_uamount: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "remove_liquidity_one_coin(uint256,int128,uint256,bool)"(
      _token_amount: BigNumberish,
      i: BigNumberish,
      min_uamount: BigNumberish,
      donate_dust: boolean,
      overrides?: Overrides
    ): Promise<BigNumber>;

    token(overrides?: Overrides): Promise<BigNumber>;

    "token()"(overrides?: Overrides): Promise<BigNumber>;

    underlying_coins(
      arg0: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "underlying_coins(int128)"(
      arg0: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    withdraw_donated_dust(overrides?: Overrides): Promise<BigNumber>;

    "withdraw_donated_dust()"(overrides?: Overrides): Promise<BigNumber>;
  };

  populateTransaction: {
    add_liquidity(
      uamounts: [BigNumberish, BigNumberish],
      min_mint_amount: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "add_liquidity(uint256[2],uint256)"(
      uamounts: [BigNumberish, BigNumberish],
      min_mint_amount: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    calc_withdraw_one_coin(
      _token_amount: BigNumberish,
      i: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "calc_withdraw_one_coin(uint256,int128)"(
      _token_amount: BigNumberish,
      i: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    coins(
      arg0: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "coins(int128)"(
      arg0: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    curve(overrides?: Overrides): Promise<PopulatedTransaction>;

    "curve()"(overrides?: Overrides): Promise<PopulatedTransaction>;

    remove_liquidity(
      _amount: BigNumberish,
      min_uamounts: [BigNumberish, BigNumberish],
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "remove_liquidity(uint256,uint256[2])"(
      _amount: BigNumberish,
      min_uamounts: [BigNumberish, BigNumberish],
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    remove_liquidity_imbalance(
      uamounts: [BigNumberish, BigNumberish],
      max_burn_amount: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "remove_liquidity_imbalance(uint256[2],uint256)"(
      uamounts: [BigNumberish, BigNumberish],
      max_burn_amount: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "remove_liquidity_one_coin(uint256,int128,uint256)"(
      _token_amount: BigNumberish,
      i: BigNumberish,
      min_uamount: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "remove_liquidity_one_coin(uint256,int128,uint256,bool)"(
      _token_amount: BigNumberish,
      i: BigNumberish,
      min_uamount: BigNumberish,
      donate_dust: boolean,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    token(overrides?: Overrides): Promise<PopulatedTransaction>;

    "token()"(overrides?: Overrides): Promise<PopulatedTransaction>;

    underlying_coins(
      arg0: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "underlying_coins(int128)"(
      arg0: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    withdraw_donated_dust(overrides?: Overrides): Promise<PopulatedTransaction>;

    "withdraw_donated_dust()"(
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;
  };
}
