/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer } from "ethers";
import { Provider } from "@ethersproject/providers";

import type { ICurveZapIbBTC } from "./ICurveZapIbBTC";

export class ICurveZapIbBTCFactory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ICurveZapIbBTC {
    return new Contract(address, _abi, signerOrProvider) as ICurveZapIbBTC;
  }
}

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_pool",
        type: "address",
      },
      {
        internalType: "uint256[4]",
        name: "_deposit_amounts",
        type: "uint256[4]",
      },
      {
        internalType: "uint256",
        name: "_min_mint_amount",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "_receiver",
        type: "address",
      },
    ],
    name: "add_liquidity",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
];
