/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface TrancheGovernanceInterface extends ethers.utils.Interface {
  functions: {
    "editTranche(uint8,uint8,uint256,uint256)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "editTranche",
    values: [BigNumberish, BigNumberish, BigNumberish, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "editTranche",
    data: BytesLike
  ): Result;

  events: {};
}

export class TrancheGovernance extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: TrancheGovernanceInterface;

  functions: {
    editTranche(
      trancheId: BigNumberish,
      _riskLevel: BigNumberish,
      _variableBorrowRateMultiplier: BigNumberish,
      _stableBorrowRateMultiplier: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "editTranche(uint8,uint8,uint256,uint256)"(
      trancheId: BigNumberish,
      _riskLevel: BigNumberish,
      _variableBorrowRateMultiplier: BigNumberish,
      _stableBorrowRateMultiplier: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;
  };

  editTranche(
    trancheId: BigNumberish,
    _riskLevel: BigNumberish,
    _variableBorrowRateMultiplier: BigNumberish,
    _stableBorrowRateMultiplier: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "editTranche(uint8,uint8,uint256,uint256)"(
    trancheId: BigNumberish,
    _riskLevel: BigNumberish,
    _variableBorrowRateMultiplier: BigNumberish,
    _stableBorrowRateMultiplier: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  callStatic: {
    editTranche(
      trancheId: BigNumberish,
      _riskLevel: BigNumberish,
      _variableBorrowRateMultiplier: BigNumberish,
      _stableBorrowRateMultiplier: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "editTranche(uint8,uint8,uint256,uint256)"(
      trancheId: BigNumberish,
      _riskLevel: BigNumberish,
      _variableBorrowRateMultiplier: BigNumberish,
      _stableBorrowRateMultiplier: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    editTranche(
      trancheId: BigNumberish,
      _riskLevel: BigNumberish,
      _variableBorrowRateMultiplier: BigNumberish,
      _stableBorrowRateMultiplier: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "editTranche(uint8,uint8,uint256,uint256)"(
      trancheId: BigNumberish,
      _riskLevel: BigNumberish,
      _variableBorrowRateMultiplier: BigNumberish,
      _stableBorrowRateMultiplier: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    editTranche(
      trancheId: BigNumberish,
      _riskLevel: BigNumberish,
      _variableBorrowRateMultiplier: BigNumberish,
      _stableBorrowRateMultiplier: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "editTranche(uint8,uint8,uint256,uint256)"(
      trancheId: BigNumberish,
      _riskLevel: BigNumberish,
      _variableBorrowRateMultiplier: BigNumberish,
      _stableBorrowRateMultiplier: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;
  };
}
