name: Test VMEX OPfork

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18.15.0"

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Cache node_modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Set up environment variable
        run: echo "OP_ALCHEMY_KEY=${{ secrets.OP_ALCHEMY_KEY }}" >> $GITHUB_ENV

      - name: Install Dependencies
        run: yarn install

      - name: Clean
        run: yarn contracts ci:clean

      - name: Compile
        run: yarn contracts compile

      - name: Run Hardhat node in the background
        run: |
          nohup sh -c "OP_ALCHEMY_KEY=${OP_ALCHEMY_KEY} yarn contracts vmex:node:fork:optimism > nohup.out 2>&1 &"

      - name: Wait for the Hardhat node to start
        run: sleep 30

      - name: Run deployment
        run: |
          OP_ALCHEMY_KEY=${OP_ALCHEMY_KEY} yarn contracts vmex:deploy:fork:optimism

      - name: Run deployment of ext rewards
        run: |
          OP_ALCHEMY_KEY=${OP_ALCHEMY_KEY} yarn contracts localhost:optimism:deployIncentivesController

      - name: Run tests
        run: |
          OP_ALCHEMY_KEY=${OP_ALCHEMY_KEY} yarn contracts vmex:OPfork:unit-tests

      - name: Bring Hardhat node to foreground and print logs
        run: |
          kill $(pgrep node) || true
          sleep 5
          cat nohup.out
